language: python
python:
  - 2.7
  - 3.6

install:
  - python setup.py install
  - pip install requests python-dateutil pytz

before_script:
 - chmod +x tests/test_client.py

# command to run tests
script: python tests/test_client.py
